### ISSUE TITLE
Petterssen frontogenesis

### ISSUE THREAD

**Issue by fherreazcue** [UoMResearchIT/SpanishPlumeAnalysis#15]
Convergence, Petterssen frontogenesis, vorticity in lower-troposphere warm sector to determine the prefrontal trough

**Comment by fherreazcue** [comment]
Functionality added in [86a1560](https://github.com/UoMResearchIT/SpanishPlumeAnalysis/commit/86a15605a18e6f2d68b6a80db319282ccd38a924).

**Comment by fherreazcue** [comment]
Added overlap with Potential Temperature in [9b72e3c](https://github.com/UoMResearchIT/SpanishPlumeAnalysis/commit/9b72e3c0bc830cdecb3fed76c5f4eb2e1e6f704a)

**Comment by fherreazcue** [comment]
Results shared in [dropbox](https://www.dropbox.com/scl/fo/m84hnhx0z35gpsd7ymuvb/h?rlkey=fj6m6u8xg96ynt5rd4xvdau1o&dl=0)

**Comment by douglowe** [comment]
Now you've written this function I've dug out the code Jonathan wrote in NCL to do similar:
https://github.com/UoMResearchIT/manunicast_operational_scripts/blob/5b7d3f70f01c71766d62b4aaaa0f54072faf3df4/Plotting_Scripts/WRF/wrf_3d_d01.ncl#L296
