### ISSUE TITLE
Backward trajectories from Nottingham

### ISSUE THREAD

**Issue by fherreazcue** [UoMResearchIT/SpanishPlumeAnalysis#38]
Backward trajectories from Nottingham at  

- 1200 UTC 1 July (60–0 h),  
- 1800 UTC 1 July (66–0 h),  
- 1800 UTC 3 July (114–54 h, 114–0 h), and  
- 0000 UTC 4 July (120–54 h, 120–0 h).   

Ending locations at 950, 925, 900, 850, 800, 750, 700, 650, 600, 500, 400, 300, and 250 hPa. 

 
Simulations: Control, ALB-40, ALB-Std, ALB-90 

Plots and CSV file with following columns: 

- time in model simulation 
- pressure 
- latitude 
- longitude 
- height above mean sea level 
- height above model terrain 
- actual air temperature 
- potential temperature 
- equivalent potential temperature 
- dewpoint temperature 
- mixing ratio 
- relative humidity

**Comment by fherreazcue** [comment]
The diagnostic names that can in principle be extracted from rip
- time in model simulation
- pressure:
  **_prs_**: Pressure, mb. (3D)
- ? latitude
  **_xlat_**: Latitude (if available as a separate RIP data file). (2D)
- ? longitude
  **_xlon_**: Longitude (if available as a separate RIP data file). (2D)
- ? height above mean sea level
  **_ght_**: Geopotential height above mean sea level, m. (3D)
- ? height above model terrain
  **_ghtagl_**: Geopotential height above ground level, m. (3D)
  **_ter_**: Terrain height, m. (2D)
- actual air temperature
  **_tmk_**: Temperature, K. (3D)
- potential temperature
  **_the_**: Potential temperature, K. (3D)
- equivalent potential temperature
  **_eth_**: Equivalent potential temperature, K. (3D)
- dewpoint temperature
  **_tdk_**: Dew point temperature, K. (3D)
- ? mixing ratio
  **_qci_**: Cloud ice mixing ratio, g kg-1. (3D). -- Note: If non-mixed-phase microphysics was used, this field contains the model output cloud water only where T < 0 °C, and is zero where T > 0 °C.
  **_qcl_**: Total cloud mixing ratio, g kg-1. (3D). -- Note: This is just qcw + qci.
  **_qcw_**: Cloud water mixing ratio, g kg-1. (3D). -- Note: If non-mixed-phase microphysics was used, this field contains the model output cloud water where T > 0 °C, and is zero where T < 0 °C.
  **_qgr_**: Graupel mixing ratio (if available as a separate RIP data file), g kg-1. (3D)
  **_qpr_**: Total precipitation hydrometeor mixing ratio, g kg-1. (3D). -- Note: This is just qra + qsn (+ qgr if available).
  **_qra_**: Rain water mixing ratio, g kg-1. (3D). -- Note: If non-mixed-phase microphysics was used, this field contains the model output rain water only where T > 0 °C., and is zero where T < 0 °C.
  **_qsn_**: Snow mixing ratio, g kg-1. (3D). -- Note: If non-mixed-phase microphysics was used, this field contains the model output rain water only where T < 0 °C, and is zero where T > 0 °C.
  **_qvp_**: Water vapor mixing ratio, g kg-1. (3D)
- ? relative humidity
  **_rhi_**: Relative humidity with respect to ice, percent. (3D)
  **_rhu_**: Relative humidity with respect to liquid water, percent. (3D)

**Comment by douglowe** [comment]
1. Latitude and Longitude can be the xlat / xlon values
2. Height above mean sea level / terrain needs calculating from the ght, I'll post something below (once I've looked it up)
3. mixing ratio I would usually assume should be water vapor mixing ratio (qvp) - but double check this with Dave
4. relative humidity is most commonly expressed with regards to liquid water (rhu), I think that's a safe bet to use

**Comment by douglowe** [comment]
This is the code from the NCL routine to get the height data:
```
  if( any( variable .eq. (/"geopt","geopotential","z","height", "height_agl"/) ) ) then
       ; Height [=full geopotentail height / 9.81]
       if(isfilevar(nc_file,"PH")) then
         var = _get_wrf_var(file_handle,"PH",time)
         PHB = _get_wrf_var(file_handle,"PHB",time)
         var = var + PHB
         z = wrf_user_unstagger(var,var@stagger)
         z@description = "Geopotential"
       elseif(isfilevar(nc_file,"GHT")) then
         ;; may be a met_em file - see if we can get GHT - data in met_em file is Height in M
         z = _get_wrf_var(file_handle,"GHT",time)
         z = z * 9.81
         z@description = "Geopotential"
         z@units       = "m2 s-2"
       else
         print("wrf_user_getvar: Error: cannot find 'PH' or 'GHT' on the file")
         return
       end if

       if( any( variable .eq. (/"z","height", "height_agl"/) ) ) then
         z = z / 9.81
         z@description = "Height"
         if (variable .eq. "height_agl") then
           if (isfilevar(nc_file,"HGT") ) then
             ter = _get_wrf_var(file_handle, "HGT", time)
             
             rank := dimsizes(dimsizes(ter))

             if (rank .eq. 2) then
                ter_conform = conform_dims(dimsizes(z), ter, (/1,2/))
             elseif (rank .eq. 3) then
                ter_conform = conform_dims(dimsizes(z), ter, (/0,2,3/))
             elseif (rank .eq. 4) then
                ter_conform = conform_dims(dimsizes(z), ter, (/0,1,3,4/))
             elseif (rank .eq. 5) then
                ter_conform = conform_dims(dimsizes(z), ter, (/0,1,2,4,5/))
             elseif (rank .eq. 6) then
                ter_conform = conform_dims(dimsizes(z), ter, (/0,1,2,3,5,6/))
             end if
             
             z = z - ter_conform
             z@description = "Height_AGL"
           else
             print("wrf_user_getvar: Error: cannot find 'HGT' in the file")
             return
           end if 
         end if 
         z@units       = "m"
       end if
       return(z)
  end if
```

**Comment by douglowe** [comment]
Looks like the process to get height above sea level is:
1) Add PH + PHB
2) Unstagger the grid of the resultant data
3) Divide by gravitational acceleration rate (9.81 m/s^2)

**Comment by douglowe** [comment]
Ahh - looks like RIP already returns GHT though - so perhaps just use that.

(I had assumed these were wrfout variables listed here, but perhaps RIP does this postprocessing work too)

**Comment by fherreazcue** [comment]
All diagnostics added in https://github.com/UoMResearchIT/SpanishPlumeAnalysis/commit/beef8cfefe374e55bbb6f63ac51469313e6ed38a, ready to be run on csf.
However, some issues with memory were encountered on local tests (see [this comment](https://github.com/UoMResearchIT/SpanishPlumeAnalysis/commit/beef8cfefe374e55bbb6f63ac51469313e6ed38a#diff-6fde5e9b5fc2b7a21f95232637d8141905962c57d1388792c39a67cf9321b44aR26)), so it might be that we need to run the trajectory calculation twice to get all the desired diagnostics.
Before changing the code though, I need to see if the same problem is encountered when ran on the csf.

**Comment by fherreazcue** [comment]
CSV files along trajectories of 90h ran successfully, results are in [Dropbox](https://www.dropbox.com/scl/fo/6ttynm9j57kiwyxkiam02/AMcmngtxa0wG3nvqT1-c7Eo?rlkey=20sbxqgr4akema8p08fbf3izs&dl=0).
